theme: jekyll-theme-cayman
title: [VGQ-CNN]
description: [Moving Beyond Fixed Cameras and Top-Grasps for Grasp Quality Prediction]
show_downloads: [true]
github:
  data_url: https://doi.org/10.5281/zenodo.6606333
  code_url: https://github.com/AuCoRoboticsMU/vgq-cnn